version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-openbci}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-openbci}
      POSTGRES_DB: ${POSTGRES_DB:-openbci}
    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-openbci}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
